name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: build
        run: make build
      - name: Sanity test
        run: |
          pip install dist/*.whl --force-reinstall
      - name: create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
      - name: upload to pypi
        run: make publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
